Update api_tests.yml

diff --git a/.github/workflows/api_tests.yml b/.github/workflows/api_tests.yml
--- a/.github/workflows/api_tests.yml
+++ b/.github/workflows/api_tests.yml
@@ -28,40 +28,59 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: "3.10"
-      - run: >
+      - name: Download artifacts
+        run: |
           SITE_ARTIFACT_RESPONSE=$(curl -L -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           "https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts?name=_site")
+          
           echo "Site artifact response: $SITE_ARTIFACT_RESPONSE"
-          SITE_ARTIFACT_ID=$(echo $SITE_ARTIFACT_RESPONSE | python -c "import sys, json; artifacts = json.load(sys.stdin).get('artifacts', []); \
-          print(artifacts[0]['id'] if artifacts else '');"
-          &&
+          
+          SITE_ARTIFACT_ID=$(echo $SITE_ARTIFACT_RESPONSE | python -c "import sys, json; \
+          artifacts = json.load(sys.stdin).get('artifacts', []); \
+          print(artifacts[0]['id'] if artifacts else '');")
+          
+          if [ -z "$SITE_ARTIFACT_ID" ]; then
+              echo "Error: No artifacts found with name '_site'"
+              exit 1
+          fi
+          
           curl -L -H "Accept: application/vnd.github+json" \
           -H "Authorization: ***" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts/$SITE_ARTIFACT_ID/zip \
           -o site_artifacts.zip
+          
           PAGES_ARTIFACT_RESPONSE=$(curl -L -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           "https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts?name=github_pages")
+          
           echo "GitHub Pages artifact response: $PAGES_ARTIFACT_RESPONSE"
-          PAGES_ARTIFACT_ID=$(echo $PAGES_ARTIFACT_RESPONSE | python -c "import sys, json; artifacts = json.load(sys.stdin).get('artifacts', []); \
-          print(artifacts[0]['id'] if artifacts else '');") &&
+          
+          PAGES_ARTIFACT_ID=$(echo $PAGES_ARTIFACT_RESPONSE | python -c "import sys, json; \
+          artifacts = json.load(sys.stdin).get('artifacts', []); \
+          print(artifacts[0]['id'] if artifacts else '');")
+          
+          if [ -z "$PAGES_ARTIFACT_ID" ]; then
+              echo "Error: No artifacts found with name 'github_pages'"
+              exit 1
+          fi
+          
           curl -L -H "Accept: application/vnd.github+json" \
           -H "Authorization: ***" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts/$PAGES_ARTIFACT_ID/zip \
           -o pages_artifacts.zip
-      - run: mkdir allure-results && unzip artifacts.zip -d allure-results
-      - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history
+      - run: mkdir allure-results && unzip site_artifacts.zip -d allure-results
+      - run: mkdir old_pages pages_history && unzip pages_artifacts.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history
       - run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results
       - name: Store allure history
         uses: actions/upload-artifact@v3
         with:
           name: allure-results
-          path:
-            allure-results
+          path: allure-results
           retention-days: 1
+
   run-tests:
     runs-on: ubuntu-latest
     name: Run autotests
@@ -73,7 +92,7 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
-      - name: Install dependencies.
+      - name: Install dependencies
         run: pip install -r requirements.txt
       - name: run all tests
         if: "github.event.inputs.deployment_target == 'all'"
@@ -97,7 +116,10 @@ jobs:
           distribution: 'microsoft'
           java-version: '17'
       - name: Install Allure
-        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz && sudo tar -zxvf allure-2.24.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
+        run: |
+          sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
+          sudo tar -zxvf allure-2.24.1.tgz -C /opt/
+          sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
       - name: Generate report
         run: allure generate -c allure-results -o _site
       - name: Save allure report
