Update api_tests.yml

diff --git a/.github/workflows/api_tests.yml b/.github/workflows/api_tests.yml
--- a/.github/workflows/api_tests.yml
+++ b/.github/workflows/api_tests.yml
@@ -29,30 +29,25 @@ jobs:
         with:
           python-version: "3.10"
       - run: >
-          ARTIFACT_ID=$(curl -L 
-          -H "Accept: application/vnd.github+json" 
-          -H "X-GitHub-Api-Version: 2022-11-28" 
-          "https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts?name=allure-results" 
-          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
-          &&
-          curl -L 
-          -H "Accept: application/vnd.github+json" 
-          -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
-          -H "X-GitHub-Api-Version: 2022-11-28" 
-          https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts/$ARTIFACT_ID/zip 
-          -o artifacts.zip &&
-          REPORT_ID=$(curl -L 
-          -H "Accept: application/vnd.github+json" 
-          -H "X-GitHub-Api-Version: 2022-11-28" 
-          "https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts?name=github-pages" 
-          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
-          &&
-          curl -L 
-          -H "Accept: application/vnd.github+json" 
-          -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
-          -H "X-GitHub-Api-Version: 2022-11-28" 
-          https://api.github.com/repos/senior-tester/run-tests-demo/actions/artifacts/$REPORT_ID/zip 
-          -o pages.zip
+          SITE_ARTIFACT_RESPONSE=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts?name=_site")
+          echo "Site artifact response: $SITE_ARTIFACT_RESPONSE"
+          SITE_ARTIFACT_ID=$(echo $SITE_ARTIFACT_RESPONSE | python -c "import sys, json; artifacts = json.load(sys.stdin).get('artifacts', []); print(artifacts[0]['id'] if artifacts else '');")
+          if [ -z "$SITE_ARTIFACT_ID" ]; then
+          echo "Error: No artifacts found with name '_site'"
+          exit 1
+          fi
+
+          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: ***" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts/$SITE_ARTIFACT_ID/zip -o site_artifacts.zip
+
+          PAGES_ARTIFACT_RESPONSE=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts?name=github_pages")
+          echo "GitHub Pages artifact response: $PAGES_ARTIFACT_RESPONSE"
+          PAGES_ARTIFACT_ID=$(echo $PAGES_ARTIFACT_RESPONSE | python -c "import sys, json; artifacts = json.load(sys.stdin).get('artifacts', []); print(artifacts[0]['id'] if artifacts else '');")
+          if [ -z "$PAGES_ARTIFACT_ID" ]; then
+          echo "Error: No artifacts found with name 'github_pages'"
+          exit 1
+          fi
+
+          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: ***" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts/$PAGES_ARTIFACT_ID/zip -o pages_artifacts.zip
       - run: mkdir allure-results && unzip artifacts.zip -d allure-results
       - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history
       - run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results
