Update run_tests.yml

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -28,15 +28,34 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: "3.10"
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '20'
-      - run: >
-          ARTIFACT_ID=$(curl -L -H "Accept: application/vnd.github+json" 
-          -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts?name=allure-report" 
-          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") && curl -L -H "Accept: application/vnd.github+json" > -H "Authorzation: Bearer ${{ secrets.TOKEN }}" -H "X-GitHub-Api_version: 2022-11-28" https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts/$ARTIFACT_ID/zip -o artifacts.zip
-      - run: mkdir allure-results && unzip artifacts.zip -d allure-results
+
+      - name: Get Artifact ID
+        run: |
+          ARTIFACT_ID=$(curl -L -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts?name=allure-report" \
+            | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
+          echo "Artifact ID: $ARTIFACT_ID"
+          if [ -z "$ARTIFACT_ID" ]; then
+            echo "Failed to retrieve artifact ID"
+            exit 1
+          fi
+
+      - name: Download Artifact
+        run: |
+          curl -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer 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" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -o artifacts.zip \
+            "https://api.github.com/repos/tatyana-evtikhova/automated_testing_projects/actions/artifacts/$ARTIFACT_ID/zip"
+          if [ ! -f "artifacts.zip" ]; then
+            echo "Failed to download artifact"
+            exit 1
+          fi
+
+      - name: Extract Artifact
+        run: mkdir allure-results && unzip -q artifacts.zip -d allure-results
+
       - name: Store Allure History
         uses: actions/upload-artifact@v3
         with:
